stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
  - deployment: VMDeploy
    displayName: green
    pool:
      vmImage: 'Ubuntu-18.04'
    environment:
      name: Development
      resourceType: VirtualMachine
      tags: green
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Downloading the source code from Azure blob storage container to the Azure VM..."
              sudo az storage blob download --account-name mydemoaccount001 --container-name application-container --name test-application.zip --file /opt/test-application
              echo "Extracting the source code and setting up the application to the Azure VM..."
- stage: Deploy_TM
  displayName: TM update weight stage
  jobs:
  - job: Deploy
    displayName: Deploy
  - deployment: VMDeploy
    displayName: green
    pool:
      vmImage: 'Ubuntu-18.04'
    environment:
      name: Development
      resourceType: VirtualMachine
      tags: green
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              /bin/bash /opt/test-application/scripts/blue_green_weightage.sh